spring:
  application:
    name: lifelog

  jpa:
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:postgresql://localhost:5432/lifelog
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

flyway:
  enabled: true
  locations: classpath:db/migration
  baseline-on-migrate: true
  baseline-version: 1
