version: '3'

volumes:
  lifelog-pg-data: { }

networks:
  lifelog-compose-network:
    driver: bridge

services:
  postgres:
    image: postgres:15
    restart: always
    shm_size: 128mb
    volumes:
      - lifelog-pg-data:/var/lib/postgresql
    networks:
      - lifelog-compose-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lifelog
    ports:
      - 5432:5432